### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by adahms** [redhat-documentation/community-contribution-template#1]
Write a short introduction to the guide that outlines the purpose of the guide, the intended audience, and the high-level topics for which the guide provides guidance.

**Comment by nengard** [comment]
Done : https://github.com/redhat-documentation/community-contribution-template/commit/38b582ed81d66f5a41384b594f5591426acaa08e

**Comment by adahms** [comment]
@nengard - Thanks for taking a look at this issue.

My apologies for not being clearer in the description, but this issue is actually for the framework itself, so I think we need a more general introduction to what the single-sourcing framework is and does, and the intended audience of the guidance.

Issues also need to be submitted as a PR from a forked version of the project.

I'll re-open this for now, and let me know if you have any questions!

**Comment by nengard** [comment]
Oops, new commit : https://github.com/redhat-documentation/community-contribution-template/commit/38b582ed81d66f5a41384b594f5591426acaa08e

**Comment by nengard** [comment]
Oops, new commit: https://github.com/redhat-documentation/community-contribution-template/pull/15

**Comment by nengard** [comment]
New commit https://github.com/redhat-documentation/community-contribution-template/pull/30

**Comment by adahms** [comment]
#30 has now been merged; closing.
