### ISSUE TITLE
GitBook

### ISSUE THREAD

**Issue by adahms** [redhat-documentation/community-contribution-template#11]
Write a detailed overview of GitBook, and its advantages and disadvantages in terms of the framework in the '=== GitBook' section of the supported_tools.adoc file.

**Comment by nengard** [comment]
Where were you thinking this would go? Under

=== Supported Tools and Formats

OR

=== Unsupported Tools and Formats

**Comment by nengard** [comment]
Nevermind, there was an update yesterday :)

**Comment by nengard** [comment]
Pull request: https://github.com/redhat-documentation/community-contribution-template/pull/17

**Comment by adahms** [comment]
Thank you for taking a look at this one, @nengard 

The PR has now been merged, so I am now closing this issue.
