### ISSUE TITLE
Add an example of how to publish content using Asciidoctor+Docker+Travis+gh-pages

### ISSUE THREAD

**Issue by adahms** [redhat-documentation/community-contribution-template#20]
A description of how to publish content using the RPM packaging method must be added to the '==== RPM Packaging' section of the 'structure.adoc' file. This includes a brief introduction to the method and how it works, and a link to a location where readers can find more information.

**Comment by adahms** [comment]
Assigning to Petr for review.

**Comment by nengard** [comment]
This content is now living in the publishing.adoc file.
