### ISSUE TITLE
All headings must have IDs

### ISSUE THREAD

**Issue by fbolton** [redhat-documentation/community-contribution-template#22]
According to our Asciidoc standards, headings should include an ID, which is defined by specifying the ID inside double square brackets, `[[`, `]]`, on the line preceding the heading. For example:

```
[[ccg-create-repo-synch-batchcommit]]
==== Batch Commit Synchronization Method
```

This is important for providing a clean structure for making cross-references within the document and is highly recommended for the Pantheon toolchain. I believe it has even been suggested that IDs might be made compulsory.

The work for this issue involves adding IDs to all of the headings in the existing document skeleton.

**Comment by nengard** [comment]
Resolved (we'll probably have to do this again as we add more content and folks forget IDs.
