### ISSUE TITLE
Add an example of how to publish content using GitHub Pages

### ISSUE THREAD

**Issue by nengard** [redhat-documentation/community-contribution-template#39]
A description of how to publish content using Github pages must be added to the '==== GitHub Pages' section of the 'publishing.adoc' file. This includes a brief introduction to the method and how it works, and a link to a location where readers can find more information.

**Comment by pmkovar** [comment]
FYI, #20 is an example of how to publish with GitHub pages.

**Comment by nengard** [comment]
Awesome, closing.
