### ISSUE TITLE
AsciiDoc Attributes

### ISSUE THREAD

**Issue by adahms** [redhat-documentation/community-contribution-template#5]
Write a detailed overview of the use of AsciiDoc attributes in the framework in the '=== AsciiDoc Attributes' section of the structure.adoc file.

This overview must describe the following topics:

- How to define AsciiDoc attributes in the 'brand' AsciiDoc attribute file in the common directory
- How to include the 'brand' AsciiDoc attribute file in the master.adoc file
- Common AsciiDoc attributes (product name, product name abbreviation, version)

**Comment by nengard** [comment]
@lbopf you might find a lot of useful stuff in our doc attributes for AMQ 7 : https://gitlab.cee.redhat.com/AMQ7-documentation/amq7-documentation/raw/master/docs/topics/templates/document-attributes.adoc because we have so many modules we use a lot of attributes.

**Comment by adahms** [comment]
This issue is addressed in #9 

Closing.
