### ISSUE TITLE
Contributing to the framework

### ISSUE THREAD

**Issue by adahms** [redhat-documentation/community-contribution-template#8]
Write a detailed overview of how to contribute to the framework in the '== Contributing to the Framework' section of the contributing_to_the_framework.adoc file.

This section must contain two sub-sections that cover the following topics:

* How to propose a change
* How to propose an edit to the document

**Comment by adahms** [comment]
@sjay72 - We don't really have a detailed method for proposing changes just yet, so perhaps we can just recommend raising an issue for now. As for proposing an edit to the document, a very general procedure on how to fork the project and create a topic branch should be sufficient.

Let me know if you have any questions or concerns.

**Comment by sjay72** [comment]
@adahms, thank you for the detailed request. I understand my mission and have added it to my to-do list.
